### ISSUE TITLE
Failed to resolve import +layout.vue file

### ISSUE THREAD

**Issue by swallowcc** [Shyam-Chen/Vue-Starter#93]
Hello, last time I received your assistance, and I'm very grateful for that.

Currently, one of my colleagues has joined the development team, but he's using Windows 11 for development. 
He's encountering an issue where, every time he runs 'pnpm dev' and opens the browser, he encounters the following error. 
I've tried several times but haven't been able to resolve it.

So, I decided to directly download the project you have on GitHub and ran 'pnpm i' and 'pnpm dev.' 
Unfortunately, we still face the same error. 
Have you come across a similar issue or do you know how to resolve this problem?

I'm sorry to trouble you again, and thank you.

[vite] Internal server error: Failed to resolve import "src/routes/(portal)/+layout.vue" from "virtual:vue-routes". Does the file exist?
  Plugin: vite:import-analysis
  File: virtual:vue-routes:4:31
  2  |    {
  3  |      "path": "src/routes/+",
  4  |      "component": () => import('src/routes/(portal)/+layout.vue'),
     |                                ^
  5  |      "children": [
  6  |        {
      at formatError (file:///E:/codespaces/Vue-Starter/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.8_sass@1.69.4/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44062:46)
      at TransformContext.error (file:///E:/codespaces/Vue-Starter/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.8_sass@1.69.4/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44058:19)
      at normalizeUrl (file:///E:/codespaces/Vue-Starter/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.8_sass@1.69.4/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41844:33)
      at async file:///E:/codespaces/Vue-Starter/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.8_sass@1.69.4/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41998:47
      at async Promise.all (index 0)
      at async TransformContext.transform (file:///E:/codespaces/Vue-Starter/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.8_sass@1.69.4/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:41914:13)
      at async Object.transform (file:///E:/codespaces/Vue-Starter/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.8_sass@1.69.4/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44352:30)
      at async loadAndTransform (file:///E:/codespaces/Vue-Starter/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.8_sass@1.69.4/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55026:29)
      at async viteTransformMiddleware (file:///E:/codespaces/Vue-Starter/node_modules/.pnpm/vite@4.5.0_@types+node@20.8.8_sass@1.69.4/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:64430:32) (x5)

**Comment by Shyam-Chen** [comment]
> https://github.com/Vanilla-IceCream/vite-plugin-vue-routes

In Windows, it appears that the path needs to retain its original form.

**Comment by swallowcc** [comment]
I'm sorry, I'm not sure which part needs to be modified.

**Comment by Shyam-Chen** [comment]
Next week, I'll borrow a Windows machine to give it a try, or perhaps you could consider using WSL (Windows Subsystem for Linux).

**Comment by swallowcc** [comment]
Thank you again for your assistance. 
Next Monday, I will have my colleague try to install WSL to address the path issue.

On the other hand, I'm looking forward to your testing and hope for positive results. 
Thank you.

**Comment by Shyam-Chen** [comment]
The path issue on Windows has been fixed, and you can now fetch the new or updated version of `vite-plugin-vue-routes` to v1.0.5.

**Comment by Shyam-Chen** [comment]
If there are no issues when running it, I will close the issue.

**Comment by swallowcc** [comment]
It is working fine now. Thank you very much for your assistance.
